### ISSUE TITLE
[not an issue] native & scripting implementation

### ISSUE THREAD

**Issue by inlife** [mathewmariani/sqx_require#1]
Hello there @mathewmariani,  

You've made a nice lightweight project! I will probably use that native require next time I'm gonna work with squirrel vm. 

Also i wanted to share with you, similar thing i made, but using scripting side, which also works almost exactly like the one from node.js.

https://github.com/inlife/squirrel-require

I hope that it might be helpful for you too.
Thank you!

**Comment by mathewmariani** [comment]
I'm still looking for a nice native solution add a path, much like in Lua. I will also probably take inspiration from your project and implement a couple features.

Thank you for sharing this with me!
